AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Template for continuous deployment of lambdas

# https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 180
    Runtime: python3.8
    Handler: app.lambda_handler
    Architectures:
        - x86_64

# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html
Parameters:
  Role:
    Type: String
    Description: The lambda role ARN

# https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
Resources:
  HelloEarthFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: hello-earth-lambda
      CodeUri: hello_earth/
      Role: { "Ref" : "Role" }

  HelloMarsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: hello-mars-lambda
      CodeUri: hello_mars/
      Role: { "Ref" : "Role" }
