AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Template for continuous deployment of lambdas

# https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 180
    Runtime: python3.8
    Handler: app.lambda_handler
    Architectures:
        - x86_64

# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html
Parameters:
  Role:
    Type: String
    Default: arn:aws:iam::324043197527:role/CornellLambdaRole
    AllowedValues:
      - arn:aws:iam::324043197527:role/CornellLambdaRole # default
      - arn:aws:iam::892299720529:role/CornellLambdaRole # rpm-dev
      - arn:aws:iam::172165254225:role/CornellLambdaRole # rpm-prod
      - arn:aws:iam::673897531687:role/CornellLambdaRole # etl-dev
      - arn:aws:iam::467971947892:role/CornellLambdaRole # etl-prod
    Description: The lambda role ARN.

  Env:
    Type: String
    Default: test
    AllowedValues:
      - test
      - test
    Description: The environment that the lambdas belong to.

# https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
Resources:
  HelloEarthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_earth/
      Role: { "Ref" : "Role" }

  HelloMarsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_mars/
      Role: { "Ref" : "Role" }
