AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  github-actions-with-aws-sam

  Sample SAM Template for github-actions-with-aws-sam

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  HelloEarthFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_earth/
      Handler: app.lambda_handler
      Runtime: python3.8
      Role: arn:aws:iam::324043197527:role/CornellLambdaRole
      Architectures:
        - x86_64

  HelloMarsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_earth/
      Handler: app.lambda_handler
      Runtime: python3.8
      Role: arn:aws:iam::324043197527:role/CornellLambdaRole
      Architectures:
        - x86_64

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloEarthFunction:
    Description: "Hello Earth Lambda Function"
    Value: !GetAtt HelloEarthFunction.Arn

  HelloMarsFunction:
    Description: "Hello Mars Lambda Function"
    Value: !GetAtt HelloMarsFunction.Arn
