on:
  push:
    branches:
      - dev
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      # sam build
      - run: sam build --use-container

# Run Unit tests- Specify unit tests here

# sam deploy
      - run: sam deploy --parameter-overrides Role=arn:aws:iam::673897531687:role/CornellLambdaRole Env=test --no-confirm-changeset --no-fail-on-empty-changeset --stack-name hello-planets --s3-bucket sam-cli-etl-dev --capabilities CAPABILITY_IAM --region us-west-2